/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enfermera;

import java.awt.event.ActionListener;

/**
 *
 * @author Zakaria
 */
public class EnfermeraVista extends javax.swing.JFrame {

    /**
     * Creates new form EnfermeraVista
     */
    public EnfermeraVista() {

        initComponents();

        b_administrar_medicamentos.setActionCommand("enfermeraAdministrar");
        b_buscar_medicamentos.setActionCommand("enfermeraBuscar");
        b_cerrar.setActionCommand("enfermeraCerrar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l_salir = new javax.swing.JLabel();
        b_cerrar = new java.awt.Button();
        b_administrar_medicamentos = new java.awt.Button();
        b_buscar_medicamentos = new java.awt.Button();
        l_enfermera = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(32, 35, 35));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_salir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_salir.setForeground(new java.awt.Color(57, 113, 177));
        l_salir.setText("X");
        jPanel1.add(l_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 20, 30));

        b_cerrar.setBackground(new java.awt.Color(126, 87, 194));
        b_cerrar.setFont(new java.awt.Font("Century Gothic", 0, 12));
        b_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        b_cerrar.setLabel("Cerrar");
        jPanel1.add(b_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 340, 50));

        b_administrar_medicamentos.setBackground(new java.awt.Color(126, 87, 194));
        b_administrar_medicamentos.setFont(new java.awt.Font("Century Gothic", 0, 12));
        b_administrar_medicamentos.setForeground(new java.awt.Color(255, 255, 255));
        b_administrar_medicamentos.setLabel("Administrar Medicamentos");
        b_administrar_medicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_administrar_medicamentosActionPerformed(evt);
            }
        });
        jPanel1.add(b_administrar_medicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 340, 50));

        b_buscar_medicamentos.setBackground(new java.awt.Color(126, 87, 194));
        b_buscar_medicamentos.setFont(new java.awt.Font("Century Gothic", 0, 12));
        b_buscar_medicamentos.setForeground(new java.awt.Color(255, 255, 255));
        b_buscar_medicamentos.setLabel("Buscar Medicamentos");
        jPanel1.add(b_buscar_medicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 340, 50));

        l_enfermera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono2.png"))); // NOI18N
        jPanel1.add(l_enfermera, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_administrar_medicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_administrar_medicamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_administrar_medicamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnfermeraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnfermeraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnfermeraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnfermeraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnfermeraVista().setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button b_administrar_medicamentos;
    private java.awt.Button b_buscar_medicamentos;
    private java.awt.Button b_cerrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l_enfermera;
    private javax.swing.JLabel l_salir;
    // End of variables declaration//GEN-END:variables

    public void setActionListener(ActionListener actionListener) {

        b_administrar_medicamentos.addActionListener(actionListener);
        b_buscar_medicamentos.addActionListener(actionListener);
        b_cerrar.addActionListener(actionListener);

    }

}
