/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medico;

import java.awt.event.ActionListener;

/**
 *
 * @author Zakaria
 */
public class MedicoVista extends javax.swing.JFrame {

    /**
     * Creates new form MedicoVista
     */
    public MedicoVista() {
        initComponents();
        b_buscar_enfermedades.setActionCommand("medicoBuscar");
        b_cerrar.setActionCommand("medicoCerrar");
        b_ver_pacientes.setActionCommand("medicoPacientes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l_icono_medico = new javax.swing.JLabel();
        l_salir = new javax.swing.JLabel();
        b_cerrar = new java.awt.Button();
        b_ver_pacientes = new java.awt.Button();
        b_buscar_enfermedades = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(32, 35, 35));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_icono_medico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono1.png"))); // NOI18N
        l_icono_medico.setText("jLabel2");
        jPanel1.add(l_icono_medico, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 63, -1));

        l_salir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_salir.setForeground(new java.awt.Color(57, 113, 177));
        l_salir.setText("X");
        jPanel1.add(l_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 20, 30));

        b_cerrar.setBackground(new java.awt.Color(126, 87, 194));
        b_cerrar.setFont(new java.awt.Font("Century Gothic", 0, 12));
        b_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        b_cerrar.setLabel("Cerrar");
        jPanel1.add(b_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 340, 50));

        b_ver_pacientes.setBackground(new java.awt.Color(126, 87, 194));
        b_ver_pacientes.setFont(new java.awt.Font("Century Gothic", 0, 12));
        b_ver_pacientes.setForeground(new java.awt.Color(255, 255, 255));
        b_ver_pacientes.setLabel("Ver Pacientes");
        jPanel1.add(b_ver_pacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 340, 50));

        b_buscar_enfermedades.setBackground(new java.awt.Color(126, 87, 194));
        b_buscar_enfermedades.setFont(new java.awt.Font("Century Gothic", 0, 12));
        b_buscar_enfermedades.setForeground(new java.awt.Color(255, 255, 255));
        b_buscar_enfermedades.setLabel("Buscar Enfermedades");
        jPanel1.add(b_buscar_enfermedades, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 340, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicoVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button b_buscar_enfermedades;
    private java.awt.Button b_cerrar;
    private java.awt.Button b_ver_pacientes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l_icono_medico;
    private javax.swing.JLabel l_salir;
    // End of variables declaration//GEN-END:variables

    public void setActionListener(ActionListener actionListener) {

        b_buscar_enfermedades.addActionListener(actionListener);
        b_cerrar.addActionListener(actionListener);
        b_ver_pacientes.addActionListener(actionListener);

    }

}
